// app/layout.js (or app/root-layout.js)
import "./globals.css";
import Header from "@/shared/Header/Header";
import Footer from "@/shared/Footer/Footer";
import { Suspense } from "react";
import ClientWrapper from "@/components/ClientWrapper.js";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Web Development",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <ClientWrapper>
            <Header />
            {children}
            <Footer />
          </ClientWrapper>
        </Suspense>
        <Toaster>
          toastOptions={{
            style: {
              padding: "20px 20px",
              fontSize: "20px",
              fontFamily: "var(--font-secondary)",
              backgroundColor: "rgba(0,0,0,0.8)",
              color: "var(--primary)",
              border: "2px solid var(--primary-trans-50)"
            },
            success: {
              iconTheme: {
                primary: "var(--primary)"
              }
            }
          }}
        </Toaster>
      </body>
    </html>
  );
}
